### ISSUE TITLE
API down?

### ISSUE THREAD

**Issue by paulbellmann** [SharpBit/brawlstats#14]
Hey, first of all thanks for the nice package.
But since this morning it seems to be, that the API is down?
Is there anything we can do to help? Are you guys also the devs behind the API?

Thanks 🙂

**Comment by SharpBit** [comment]
Thanks for using my package! The API should be back up right now. If you want to report API crashes or see the API status, I recommend you join the discord server at https://discord.me/BrawlAPI

**Comment by paulbellmann** [comment]
Great thanks 👍
