### ISSUE TITLE
Python 3.6 - No such file or directory

### ISSUE THREAD

**Issue by SlimeYT** [SharpBit/brawlstats#20]
Hello, Im using Pydroid3 running python 3.6 and when I try to load BrawlStats it gives the error 2 "No such file or directory"

I will atach an image with that error[
![img_20190227_231716](https://user-images.githubusercontent.com/24621566/53530717-a49bac00-3ae8-11e9-94dd-cbbb4d7903f2.jpg)
](url)

**Comment by SharpBit** [comment]
Fixed in [v2.2.7](https://github.com/SharpBit/brawlstats/tree/v2.2.7)
