### ISSUE TITLE
```collecting aiohttp Error: could not find the version that satisfies the requirments aiohttp<3.6.0>=3.5.2 (from brawlstats)``` It says (in console) when i install the cog (in red v2 bot) from https://github.com/Gr8z/Legend-Cogs > Brawlstars Cog. 

### ISSUE THREAD

**Issue by Begginersz** [SharpBit/brawlstats#30]
**Describe the bug**

**Full Code**
Upload to https://gist.github.com if the code is too long.

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happened along with a full traceback if applicable.

**Additional context**
Python Version:
brawlstats Version:
OS (and version):

**Comment by SharpBit** [comment]
upgrade aiohttp

**Comment by Begginersz** [comment]
i am new so. so how to upgrade aiohttp in ubuntu 16.04 Gcp Terminal. i am new so idk how to do that.

**Comment by SharpBit** [comment]
`pip3 install -U aiohttp`
