### ISSUE TITLE
Response 401 when running example

### ISSUE THREAD

**Issue by erocoar** [SharpBit/brawlstats#31]
Running the example, i.e. instantiating client with a newly generated token and then any command afterwards leads to Unauthorized error. 

```py
import brawlstats as bs
client = bs.Client("token")
player = client.get_leaderboard("players")
```

This is for pip-installed brawlstats and python 3.7.1

**Comment by SharpBit** [comment]
Are you sure your token is correct? Check to make sure

**Comment by adamackerman** [comment]
This happens to me as well, trying to run example with two different newly created api tokens, only get back unauthorized. Does it take time before the tokens become valid?

**Comment by AlessioTaranto** [comment]
> This happens to me as well, trying to run example with two different newly created api tokens, only get back unauthorized. Does it take time before the tokens become valid?

same problem here

**Comment by SharpBit** [comment]
It shouldn't take time for tokens to be validated, please ask in the [API discord server](https://discord.me/BrawlAPI) and ask Zihad or 4JR

**Comment by SharpBit** [comment]
@erocoar @adamackerman Ah, I see why. Next time, please give the full error because it would've said this:
![image](https://user-images.githubusercontent.com/31069084/58748211-23371b00-8443-11e9-84e3-e91cf26e09ae.png)

You have to join the discord server to use the API: https://discord.me/BrawlAPI

**Comment by MatyiFKBT** [comment]
@SharpBit I guess you can close the issue, the solution is to join the discord server
