### ISSUE TITLE
Player.3_vs_3_victories attribute starts with number

### ISSUE THREAD

**Issue by milan252525** [SharpBit/brawlstats#37]
**Describe the bug**
In the OfficialAPI Player object there is an attribute "3_vs_3_victories". But python doesn't allow variable names to start with numbers. So it raises SyntaxError.

**Full Code**
No code needed for this

**Expected behavior**
Return amount of 3v3 victories.

**Actual behavior**
Raises SyntaxError

**Additional context**
Python Version: 3.7
brawlstats Version: v3.0.1.post1

**Comment by SharpBit** [comment]
When an attribute begins with an integer, python-box automatically prepends an "x" to the beginning. So, use `Player.x3_vs_3_victories`

Thanks for the report, I'll change it in the documentation
