### ISSUE TITLE
Realtime analysis of player data with advanced statistics.

### ISSUE THREAD

**Issue by smyaknti** [SharpBit/brawlstats#43]
**Feature Request: Realtime data gathering**

I was looking through the possibilities of the API and came across (maybe) a way to gather data in realtime because the battle log is limited to 25 items at most (referring to the data returned by the API), and tracking a battles for about 1.5 hours of play can easily surpass the 25 battles limit. I would have to poll the data and keep a track of the additions and maybe obtain an extended battle log of some sort for analysis. (I haven't thought much of the analysis part yet)

On that note another thing crossed my mind: **are there any limits imposed on the number of API calls one IP can do per hour?** I didn't find any proper details in the documentation. All that I found was located [here](https://developer.brawlstars.com/#/documentation).

**Comment by SharpBit** [comment]
No, you'd have to set up your own thing to call the API periodically.

From what I've heard you have 80 requests/second or 3200 requests per minute, whichever comes first

**Comment by smyaknti** [comment]
Well that makes it kinda difficult to call for multiple player tags from one API key. 
Any kind of suggested workaround for a large scale use? The key being IP bound is also a pain.

**Comment by SharpBit** [comment]
Why do you need to request more than 3200 times a minute? How many tags are you working with and how often do you need to check the API for each tag?

**Comment by smyaknti** [comment]
I was thinking of scalability. Have found a workaround though, you can close this issue if you want, would add a PR if I can make it work properly. :)
