### ISSUE TITLE
AttributeError: module 'brawlstats' has no attribute 'client'

### ISSUE THREAD

**Issue by eljequercin** [SharpBit/brawlstats#48]
**Describe the bug**
I'm having troubles with authenticating in the API, when I use the sync code uploaded it shows me that error

![image](https://user-images.githubusercontent.com/45019139/77305826-ff590480-6cf6-11ea-8fa5-e058f306c882.png)

**Additional context**
Python Version: 3.8
brawlstats Version: 4.0
OS (and version): Windows 10

**Comment by SharpBit** [comment]
capital C - `brawlstats.Client`

**Comment by eljequercin** [comment]
O it was that!

Thank you!
