### ISSUE TITLE
Suggestion to remove the replacement of O's with 0's

### ISSUE THREAD

**Issue by smyaknti** [SharpBit/brawlstats#49]
In the following line https://github.com/SharpBit/brawlstats/blob/d042f2be8843a8d518a1774427c2e16d4283d173/brawlstats/utils.py#L41 can the replacement of `O`'s  with `0`'s be dropped? Because it works for the API but if I take the player tag as a parameter it just breaks any other part of the script I want to use the player tag in. The API anyway returns a `0` and as there is already a check for the valid characters in place in the following line https://github.com/SharpBit/brawlstats/blob/d042f2be8843a8d518a1774427c2e16d4283d173/brawlstats/utils.py#L46 I recommend removing the `O` replacement with `0` as it kind of feels redundant. That way I can only resolve tag messups with not found error and a simple message like `your tag may be incorrect, the valid characters are 0289PYLQGRJCUV and its a Numeric Zero and not a O.`
I got 5 people who messed up their tag like this and pinged me saying that my code is broken.

You can contact me at Sammy#5535 on discord as well if you have any other suggestions as this change maybe good in some cases as well.

**Comment by SharpBit** [comment]
fixed in 4.1.0
