### ISSUE TITLE
Errors occur when upgrading from version 4.0.0 to 4.0.1

### ISSUE THREAD

**Issue by 0dminnimda** [SharpBit/brawlstats#50]
**Describe the bug**
version 4.0.1 made a mistake in the code.

**Full Code**
`import brawlstats as bs

TOKEN = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjcwNzRiZDYwLTc2ZDYtNGZjNi04NGU3LTJiNWJhZWQ2MTdkNSIsImlhdCI6MTU4NjU1MTQ5MSwic3ViIjoiZGV2ZWxvcGVyLzZlODE2NjVmLTc2MWItMjY1NS1iNzA2LTNjZjNlY2YwYTcyZSIsInNjb3BlcyI6WyJicmF3bHN0YXJzIl0sImxpbWl0cyI6W3sidGllciI6ImRldmVsb3Blci9zaWx2ZXIiLCJ0eXBlIjoidGhyb3R0bGluZyJ9LHsiY2lkcnMiOlsiOTEuNzcuMjEzLjExOSJdLCJ0eXBlIjoiY2xpZW50In1dfQ.opWpE8SR1y5jiSThwIcWzXfly83IpOoCrM46ZI6XO6VAtkS_q4xIn0XUj8rm9GG8cKIOLE472QKsQ5fsxFLebw"

my_tag = "2q0ql2pl".upper()

client = bs.Client(TOKEN)

me = client.get_player(my_tag)

print(me.raw_data['tag'])`

**Expected behavior**
output "#2Q0QL2PL"

**Actual behavior**
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    me = client.get_player(my_tag)
  File "C:\Program Files\Python38\lib\site-packages\brawlstats/utils.py", line 101, in wrapper
    return func(*new_args, **new_kwargs)
  File "C:\Program Files\Python38\lib\site-packages\brawlstats/core.py", line 205, in get_player
    return self._get_model(url, model=Player)
  File "C:\Program Files\Python38\lib\site-packages\brawlstatss/core.py", line 189, in _get_model
    return model(self, data)
TypeError: __init__() takes 1 positional argument but 3 were given

**Additional context**
Python Version: 3.8.2
brawlstats Version: 4.0.1
OS (and version): it doesn't matter since it doesn’t work both on my hosting and on my computer (after upgrading from 4.0.0 to 4.0.1)

**Comment by 0dminnimda** [comment]
it is logical to add that the problem is solved by "pip install brawlstats == 4.0.0"

**Comment by SharpBit** [comment]
Edit your initial comment and remove your token because that can be abused, never post your token publicly. Also, this should be fixed in v4.0.2

**Comment by 0dminnimda** [comment]
Thank you for your concern, I do not think that in this case it was dangerous, I thought twice to publish a token. (in any case, I wrote an already unused token)

**Comment by 0dminnimda** [comment]
in addition, if someone wants to use my token, he will not be able (in this case), because my token has in the white sheet only my ip

**Comment by 0dminnimda** [comment]
and wow, how quickly this is fixed :) version 4.0.2 is already on the network
