### ISSUE TITLE
Asyncio Lock is not awaited

### ISSUE THREAD

**Issue by izanagi1995** [SharpBit/brawlstats#55]
**Describe the bug**
Currently https://github.com/SharpBit/brawlstats/blob/master/brawlstats/core.py#L157 uses a new instance of Lock when trying to avoid rate limitation. Unfortunately, this couldn't work because you need to keep the same instance of the Lock between function calls.

See https://docs.python.org/3/library/asyncio-sync.html#asyncio.Lock

**Full Code**
N/A

**Expected behavior**
The Lock instance is preserved between calls.

**Actual behavior**
A new instance of Lock is created on every call, making it useless.

**Proposed solution**
When instantiating `Client`, add a attribute `self.lock = asyncio.Lock()` and later use `async with self.lock:` 

**Additional context**
N/A

**Comment by SharpBit** [comment]
i still need to implement the proposed solution here, kinda left the other PR on the backburner since it required python 3.6 but this is definitely doable

**Comment by SharpBit** [comment]
Fixed using the proposed solution in v4.0.5 (finally)
