### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by Ety60** [SharpBit/brawlstats#58]
I have a problem installing the API.
I tried installing the API on a raspberry pi 4 with Raspbian operating system. When I ran the command "pip install brawlstats" I kept getting this error:
Command "python setup.py egg_info" failed with error code 1 in / tmp / pip-req-build-zi_9Us /

Can anyone help me?

**Comment by SharpBit** [comment]
Try this and tell then reinstall- https://github.com/facebook/prophet/issues/418#issuecomment-359106434

**Comment by Ety60** [comment]
Thank you for the quick answer. I've tried it and my setup tools should be up to date. But now I get another error, this one: 
"could not find a version that satisfied the requirement brawlstats (from versions: )
No matching distribution found for brawlstats"

**Comment by SharpBit** [comment]
How are you installing brawlstats (what command are you running)? Make sure you're using to pip to install the package using python 3 not 2

**Comment by Ety60** [comment]
The commands I run are the following:
"git clone https://github.com/SharpBit/brawlstats.git"

"pip install brawlstats"

**Comment by jiacheng-0** [comment]
is this brawlstats API server down?

**Comment by SharpBit** [comment]
@Ety60 Cloning the repo won't do anything if you're running `pip install brawlstats` Can you type `pip show brawlstats` and tell me what version is installed?

**Comment by Ety60** [comment]
I tried `pip install brawlstats` but it doesn't return feedback. I have found the exact error now. This one:
```
Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-eBYJIw/brawlstats/setup.py", line 3, in <module>
        with open('README.rst', encoding='utf8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function

```

**Comment by SharpBit** [comment]
Please tell me what command you're running to run the program and type `pip show brawlstats` and paste the entire response here

**Comment by Ety60** [comment]
This is what I try to do, every time:
![foto_brawlstats (1)](https://user-images.githubusercontent.com/66908980/85109595-da026680-b211-11ea-8d2f-885a239e6bf3.png)

**Comment by jiacheng-0** [comment]
> @Ety60 Cloning the repo won't do anything if you're running `pip install brawlstats` Can you type `pip show brawlstats` and tell me what version is installed?

Hi there, I've ran the command and it shows Version: 4.0.2, should i uninstall that and install directly from your repo for the 4.0.3 version? Since it shows 4.0.3 is available on https://pypi.org/project/brawlstats/

**Comment by SharpBit** [comment]
@Ety60 I'm pretty sure you're trying to install brawlstats on python 2 when it's only available for python 3: Type `python --version` to double check- if it says python 2.7, try `python3 -m pip install brawlstats`

**Comment by jiacheng-0** [comment]
> @Ety60 I'm pretty sure you're trying to install brawlstats on python 2 when it's only available for python 3: Type `python --version` to double check- if it says python 2.7, try `python3 -m pip install brawlstats`

Hi SharpBit, my pc has Python 3.7.0

**Comment by SharpBit** [comment]
@jiacheng-0 I'm talking to Ety60, not you. I replied to you in issue #59- please tell me what error you're getting there

**Comment by jiacheng-0** [comment]
![image](https://user-images.githubusercontent.com/15206284/85163475-76218180-b295-11ea-96b8-fb7d313c999f.png)
Hi there attached is the screenshot of the error!

**Comment by Ety60** [comment]
@SharpBit You were right. It works now, thank you for helping me!
