### ISSUE TITLE
Client constructor accepts :url:

### ISSUE THREAD

**Issue by fourjr** [SharpBit/brawlstats#6]
**Is your feature request related to a problem? Please describe.**
When I'd like to test with for example, a self hosted API, the wrapper does not support it : (

**Describe the solution you'd like**
A `url` kwarg in Client constructor to use instead of `http://brawlapi.cf/api`

**Comment by SharpBit** [comment]
Added in [04ec73f](https://github.com/SharpBit/brawlstats/commit/04ec73f26c694f3cd84ba10fd1482b3648c82f85)
