### ISSUE TITLE
no access to general brawler information

### ISSUE THREAD

**Issue by 0dminnimda** [SharpBit/brawlstats#60]
** Is your feature request related to a problem? Please describe. **
there is no way to learn about brawlers in the module. although in the official api there is such an [opportunity](https://developer.brawlstars.com/api-docs/index.html#!/brawlers)

** Describe the solution you'd like **
add get_brawlers function with which you can get information about brawlers

** Describe alternatives you've considered **
send requests to BS api yourself

** Additional context **
do it please :(

**Comment by 0dminnimda** [comment]
as far as I understand, everyone does give a damn, well, I’ll have to do everything myself

**Comment by 0dminnimda** [comment]
resolved at https://github.com/SharpBit/brawlstats/pull/62, waiting for integration with master

**Comment by SharpBit** [comment]
#62 was merged
