### ISSUE TITLE
unnecessary print of brawlers

### ISSUE THREAD

**Issue by Duskt** [SharpBit/brawlstats#71]
dictionary containing brawler names and IDs is automatically printed to console upon client initialisation. this bug was introduced very recently and takes place at line 30 in brawlstats/utils.py in set_brawlers()
sorry for not fixing myself - i didn't want to create a fork purely for this bug

also, nice repo. has been very useful for me

**Comment by SharpBit** [comment]
Just released v4.0.5 fixing this, i had actually fixed this a few days ago but just didnt release
