### ISSUE TITLE
Every brawler in the rankings is now invalid

### ISSUE THREAD

**Issue by appleGun22** [SharpBit/brawlstats#73]
client.get_rankings(ranking = "brawlers", region=None,limit = 200, brawler='any_brawler_name')

and always the same output

  File "C:\Users\*****\AppData\Local\Programs\Python\Python38\lib\site-packages\brawlstats\core.py", line 287, in get_rankings
    raise ValueError('Invalid brawler.')
ValueError: Invalid brawler.

that code worked correctly until update 4.0.4 i guess

**Comment by SharpBit** [comment]
If you're trying to access rankings immediately after client initialization, you have to wait for the client to request the API to get the list of current brawlers. So in other words, wait a bit after client initialization (ive tested-not extensively- but it seemed to work for me after waiting 0.4 seconds)

**Comment by appleGun22** [comment]
that fixed the issue, thanks :)!

**Comment by 0dminnimda** [comment]
this if kludge, this is unacceptable

**Comment by 0dminnimda** [comment]
these actions must be performed inside the library, and not manually by the user, and this also creates a compatibility problem with earlier versions
