### ISSUE TITLE
x3vs3_victories vs team_victories

### ISSUE THREAD

**Issue by gadhagod** [SharpBit/brawlstats#80]
What's the difference between `v3v3` vs `team_victories` in the `player` object? For me, the number is the exact same. I think they mean the same thing, but please do correct me if I'm wrong.

I was wondering if this it's necessary to have both attributes.

**Comment by SharpBit** [comment]
`x3v3_victories` and `team_victories` both do the same thing, `team_victories` is just an alias since there's an awkward "x" in front of the attribute name (since python variables can't start with a number

**Comment by gadhagod** [comment]
Oh. Makes sense. Thanks for the response!

**Comment by gadhagod** [comment]
Maybe it's worth mentioning this somewhere in the docs?
