### ISSUE TITLE
Brawler Gadgets

### ISSUE THREAD

**Issue by Gamerking-BrawlStars** [SharpBit/brawlstats#83]
Currently you can only find the Star Power of a Brawler in this wrapper, but according to the official API you can already query the Gadgets. It would be good if you add the gadgets to the brawlers.

**Comment by 0dminnimda** [comment]
@Gamerking-BrawlStars I see this is your first issue if you didn’t know closed issue = some action taken (fixed, ignored or already covered elsewhere). At the moment, nothing has been done with your issue, so if you want someone to at least notice this problem, open it.
