### ISSUE TITLE
not available in brawl stats

### ISSUE THREAD

**Issue by abdumajidomonov** [SharpBit/brawlstats#88]
hello brother, I wanted to create a bot for buying gems on telegram for brawl stars, I am from Uzbekistan, it is very difficult to buy gems in Uzbekistan, so I wanted to create a telegram bot, it would be great if you could help me, if you could release the tutorials on brawl stats to youtube, it would be easier to learn, thanks in advance

**Comment by SharpBit** [comment]
This wrapper (and the API) doesn't let you buy gems
